name: sora_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8

  google_maps_flutter: ^2.3.1
  intl: ^0.17.0
  font_awesome_flutter: ^10.8.0
  meta_seo: ^3.0.9
  seo: ^0.0.10 

dev_dependencies:
  flutter_test:
    sdk: flutter

  google_fonts: ^6.3.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0 
  url_launcher: ^6.2.1
  share_plus: ^12.0.0
  shared_preferences: ^2.0.11
  flutter_launcher_icons: ^0.14.4
  # Removed seo_renderer from here

  image_picker: ^1.1.2

  http: ^1.5.0 
  cloud_firestore: ^6.0.0
  mpesa_flutter_plugin: ^1.6.1
  flutter_dotenv: ^6.0.0
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/
    - env.txt

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sora_logo.png"
  min_sdk_android: 21