// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvNmDUZYGKdoFsnhn5vfsz-STH62UNuOg',
    appId: '1:197935670341:web:0e1f1b75bb7424b6ffaf2c',
    messagingSenderId: '197935670341',
    projectId: 'sora-4f25b',
    authDomain: 'sora-4f25b.firebaseapp.com',
    storageBucket: 'sora-4f25b.firebasestorage.app',
    measurementId: 'G-Y2XNY1HQDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUy-zM8ZggucAwilnoICNmVNiK45SR85w',
    appId: '1:197935670341:android:79588250c2945b4bffaf2c',
    messagingSenderId: '197935670341',
    projectId: 'sora-4f25b',
    storageBucket: 'sora-4f25b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6PLQqEnSqO6RWG-5LZVFlbh5IkPH4ylE',
    appId: '1:197935670341:ios:ba86296a4b5c5739ffaf2c',
    messagingSenderId: '197935670341',
    projectId: 'sora-4f25b',
    storageBucket: 'sora-4f25b.firebasestorage.app',
    iosBundleId: 'com.example.soraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6PLQqEnSqO6RWG-5LZVFlbh5IkPH4ylE',
    appId: '1:197935670341:ios:ba86296a4b5c5739ffaf2c',
    messagingSenderId: '197935670341',
    projectId: 'sora-4f25b',
    storageBucket: 'sora-4f25b.firebasestorage.app',
    iosBundleId: 'com.example.soraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvNmDUZYGKdoFsnhn5vfsz-STH62UNuOg',
    appId: '1:197935670341:web:2d520a226132b063ffaf2c',
    messagingSenderId: '197935670341',
    projectId: 'sora-4f25b',
    authDomain: 'sora-4f25b.firebaseapp.com',
    storageBucket: 'sora-4f25b.firebasestorage.app',
    measurementId: 'G-E1ZGFTR2JF',
  );

}